version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: mysql_encuestas
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: encuestas_postgrado
      MYSQL_USER: admin
      MYSQL_PASSWORD: 123456
    ports:
      - "3307:3306"
    volumes:
      - mysql_data:/var/lib/mysql

  frontend:
    build: ./frontend
    ports:
      - "3000:80"
    restart: unless-stopped

  backend:
    build: ./backend
    ports:
      - "4000:4000"
    depends_on:
      - mysql
    restart: unless-stopped

volumes:
  mysql_data:
